int_libs = # Interface dependencies.
imp_libs = # Implementation dependencies.
#import imp_libs += libhello%lib{hello}

lib{mylib-versionned}: {hxx ixx txx cxx}{** -version} hxx{version} $imp_libs $int_libs

# Include the generated version header into the distribution (so that we don't
# pick up an installed one) and don't remove it when cleaning in src (so that
# clean results in a state identical to distributed).
#
hxx{version}: in{version} $src_root/manifest
hxx{version}: dist  = true
hxx{version}: clean = ($src_root != $out_root)

cxx.poptions =+ "-I$out_root" "-I$src_root"
lib{mylib-versionned}: cxx.export.poptions = "-I$out_root" "-I$src_root"

liba{mylib-versionned}: cxx.export.poptions += -DMYLIB_VERSIONNED_STATIC
libs{mylib-versionned}: cxx.export.poptions += -DMYLIB_VERSIONNED_SHARED

obja{*}: cxx.poptions += -DMYLIB_VERSIONNED_STATIC_BUILD
objs{*}: cxx.poptions += -DMYLIB_VERSIONNED_SHARED_BUILD

lib{mylib-versionned}: cxx.export.libs = $int_libs

# For pre-releases use the complete version to make sure they cannot be used
# in place of another pre-release or the final version.
#
if $version.pre_release
  lib{mylib-versionned}: bin.lib.version = @"-$version.project_id"
else
  lib{mylib-versionned}: bin.lib.version = @"-$version.major.$version.minor"

# Install into the mylib-versionned/ subdirectory of, say, /usr/include/
# recreating subdirectories.
#
{hxx ixx txx}{*}: install         = include/mylib-versionned/
{hxx ixx txx}{*}: install.subdirs = true
